#3º B Programacion Matutino
#Autor: Alexis Mora Meza
#Objetivo: saludar al usuario y most
cheque=int(input("Ingresa tu cheque"))

mil=int(cheque/1000)
r=(cheque%1000)
quin=int(r/500)
re=(r%500)
dosc=int(re/200)
res=(re%200)
cien=int(res/100)
resu=(res%100)
cinc=int(resu/50)
resul=(resu%50)
veint=int(resul/20)
result=(resul%20)
diez=int(result/10)
resulta=(result%10)
cinco=int(resulta/5)
resultad=(resulta%5)
dos=int(resultad/2)
resultado=(resultad%2)
uno=int(resultado/1)
resultados=(resultado%1)

print("billetes de 1000",mil)
print("billetes de 500",quin)
print("billetes de 200",dosc)
print("billetes de 100",cien)
print("billetes de 50",cinc)
print("billetes de 20",veint)
print("Monedas de 10",diez)
print("Monedas de 5",cinco)
print("Monedas de 2",dos)
print("Monedas de 1",uno)